# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAtbcB0zEhQh_EmdKEQg2NBWGpmvxmWu
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import numpy as np
# 
# st.title("Diabetes Prediction App")
# st.write("Enter patient details to predict risk of diabetes.")
# 
# # Load model and scaler
# with open('diabetes_model.pkl', 'rb') as f:
#     model = pickle.load(f)
# 
# with open('scaler.pkl', 'rb') as f:
#     scaler = pickle.load(f)
# 
# # Input fields
# preg = st.number_input("Number of Pregnancies", 0, 20, 0)
# glucose = st.number_input("Glucose Level", 0, 300, 120)
# bp = st.number_input("Blood Pressure", 0, 200, 70)
# skin = st.number_input("Skin Thickness", 0, 100, 20)
# insulin = st.number_input("Insulin Level", 0, 900, 80)
# bmi = st.number_input("BMI", 0.0, 70.0, 25.0)
# dpf = st.number_input("Diabetes Pedigree Function", 0.0, 3.0, 0.5)
# age = st.number_input("Age", 0, 120, 30)
# 
# # Predict
# if st.button("Predict"):
#     input_data = np.array([[preg, glucose, bp, skin, insulin, bmi, dpf, age]])
#     input_scaled = scaler.transform(input_data)
#     prediction = model.predict(input_scaled)
# 
#     if prediction[0] == 1:
#         st.error("High Risk of Diabetes! 🚨")
#     else:
#         st.success("Low Risk of Diabetes ✅")

